In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [3]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [5]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [7]:
total_revenue = np.sum(revenue_per_product).item()
total_revenue

664.62

## 2. Analyzing Block Post Stats

In [8]:
views = np.array((1000, 500, 800, 1200, 300, 600))
views

array([1000,  500,  800, 1200,  300,  600])

In [11]:
max_views = np.max(views)
max_views

np.int64(1200)

In [12]:
min_views = np.min(views).item()
min_views

300

In [32]:
average_views = np.round(np.mean(views), 2).item()
average_views

733.33

In [18]:
total_views = np.sum(views).item()
total_views

4400

## 3. Splitting Order into Batches

In [28]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [29]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [40]:
for i, batch in enumerate(batches):
    print(f"Batch number {i}:")
    print("First element in the batch: ", batch[0])
    print("Second element in the batch: ", batch[1])
    print('')

Batch number 0:
First element in the batch:  1001
Second element in the batch:  1002

Batch number 1:
First element in the batch:  1003
Second element in the batch:  1004

Batch number 2:
First element in the batch:  1005
Second element in the batch:  1006

Batch number 3:
First element in the batch:  1007
Second element in the batch:  1008



## 4. Categorizing Product Ratings

In [41]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [42]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [43]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

## Calculate Total and Average quantities sold

In [48]:
# Кожна колонка - це специфічний продукт
# Кожен ряд - це специфічне замовлення
# Перший товар купили 5 разів в 1 замовленні і 10 разів в 2 замовленні
order_quantities = np.array(([5, 3, 2, 7], [10, 6, 3, 9]))
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [56]:
# Кількість продажів на продукт
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [59]:
# Кількість продажів на замовлення
total_products_per_order = np.sum(order_quantities, axis=1)
total_products_per_order

array([17, 28])

In [62]:
# Середня кількість на продукт по усім замовленням
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

## 6. Calculate Average Product Rating and Maximum Rating per Category

In [65]:
# Кожен ряд - це один продукт
# Кожен продукт оцінюється в 4 категоріях
product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [77]:
# Середній рейтинг в кожній категорії, округлив до 1 знаку після коми
average_rating_per_category = np.mean(product_ratings, axis=0).round(1)
average_rating_per_category

array([3.6, 3.5, 2.7, 3.4])

In [78]:
# Середній рейтинг для кожного продукту, округлив до 1 знаку після коми
average_rating_per_product = np.mean(product_ratings, axis=1).round(1)
average_rating_per_product

array([3.8, 3.5, 2.7])

In [79]:
# Максимальний рейтинг в кожній категорії, округлив до 1 знаку після коми
max_rating_per_category = np.max(product_ratings, axis=0).round(1)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

## 7. Generation of the sample stock data

In [91]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open 1', 'Close 1', 'Open 2', 'Close 2']

In [92]:
# Форма буде (3, 2, 4)
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [86]:
stock_prices.shape

(3, 2, 4)

In [93]:
for index_axis_0, company in enumerate(companies):
    print(f"Stock prices for {company}:")
    for index_axis_1, day in enumerate(days):
        print(f"Day: {day}")
        for index_axis_2, price_type in enumerate(price_types):
            print(f"{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}")
        print('')
    print('')

Stock prices for Google:
Day: Mon 1 April
Open 1 Price: 0.417
Close 1 Price: 0.72
Open 2 Price: 0.0
Close 2 Price: 0.302

Day: Tue 2 April
Open 1 Price: 0.147
Close 1 Price: 0.092
Open 2 Price: 0.186
Close 2 Price: 0.346


Stock prices for Microsoft:
Day: Mon 1 April
Open 1 Price: 0.397
Close 1 Price: 0.539
Open 2 Price: 0.419
Close 2 Price: 0.685

Day: Tue 2 April
Open 1 Price: 0.204
Close 1 Price: 0.878
Open 2 Price: 0.027
Close 2 Price: 0.67


Stock prices for Apple:
Day: Mon 1 April
Open 1 Price: 0.417
Close 1 Price: 0.559
Open 2 Price: 0.14
Close 2 Price: 0.198

Day: Tue 2 April
Open 1 Price: 0.801
Close 1 Price: 0.968
Open 2 Price: 0.313
Close 2 Price: 0.692


