In [1]:
import numpy as np

In [16]:
np.arange(10).reshape([2, 5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
np.arange(10).reshape([3, 10])

ValueError: cannot reshape array of size 10 into shape (3,10)

In [19]:
np.arange(20).reshape([4, 5]).reshape([2, 2, 5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [20]:
np.random.random((10, ))

array([0.39126714, 0.0897739 , 0.75684936, 0.07981698, 0.08868144,
       0.56948768, 0.82285587, 0.46883858, 0.32008708, 0.92092904])

In [22]:
np.random.random((10, )).reshape((2, 5))

array([[0.95438758, 0.72571378, 0.26352003, 0.2062683 , 0.4035126 ],
       [0.31268687, 0.76552371, 0.55406601, 0.65344673, 0.4802754 ]])

In [24]:
np.random.seed(0)
np.random.randint(50, 80, (4, 3, 3))

array([[[62, 65, 71],
        [50, 53, 77],
        [53, 57, 59]],

       [[69, 71, 68],
        [54, 73, 56],
        [74, 74, 62]],

       [[76, 51, 56],
        [57, 73, 64],
        [74, 67, 55]],

       [[75, 63, 58],
        [59, 70, 69],
        [66, 69, 55]]], dtype=int32)

In [37]:
np.random.seed(0)
np.random.randint(50, 80, (4, 3, 3)).flatten()

array([62, 65, 71, 50, 53, 77, 53, 57, 59, 69, 71, 68, 54, 73, 56, 74, 74,
       62, 76, 51, 56, 57, 73, 64, 74, 67, 55, 75, 63, 58, 59, 70, 69, 66,
       69, 55], dtype=int32)

In [31]:
np.arange(30).reshape([3, 10]).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
np.arange(30).reshape([4, 10]).flatten()

ValueError: cannot reshape array of size 30 into shape (4,10)