In [1]:
import numpy as np

In [4]:
np.zeros([2, 4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.ones([5, 3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
np.random.random((2, 4))

array([[0.58262986, 0.95922977, 0.14583278, 0.77957746],
       [0.90239095, 0.38916788, 0.35208528, 0.21753189]])

In [19]:
np.random.seed(10)
np.random.random((3, 5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])

In [24]:
np.random.randint(10, 20, size=(2,4))

array([[11, 13, 16, 15],
       [13, 19, 16, 19]], dtype=int32)

In [30]:
np.random.seed(0)
np.random.uniform(10, 50, size=(3, 5))

array([[31.95254016, 38.60757465, 34.11053504, 31.79532732, 26.94619197],
       [35.83576452, 27.50348845, 45.67092003, 48.54651042, 25.33766075],
       [41.66900152, 31.15579679, 32.72178244, 47.02386553, 12.84144233]])

In [32]:
np.random.seed(0)
np.random.choice(np.array([1, 2, 3]), size=10)

array([1, 2, 1, 2, 2, 3, 1, 3, 1, 1])

In [33]:
np.random.seed(0)
np.random.choice(np.array(['a', 'b', 'c']), size=10)

array(['a', 'b', 'a', 'b', 'b', 'c', 'a', 'c', 'a', 'a'], dtype='<U1')